In [ ]:
#1. Create a 1D NumPy array of integers from 10 to 20.
import numpy as np
arr=np.array([10,11,12,13,14,15,16,17,18,19,20])

print(arr)
print(arr.shape)

[10 11 12 13 14 15 16 17 18 19 20]
(11,)

In [ ]:
#2. Reshape a 1D array of integers from 1 to 16 into a 4x4 matrix.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

newarr=arr.reshape(4,4)
print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

In [ ]:
#3.  Create a 2D array of shape (4, 5) with integers from 1 to 20 and access the element in the 3rd row and 4th column.
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

print(arr)
print(arr.shape)
print('The element in the 3rd row and 4th column',arr[2,3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)
The element in the 3rd row and 4th column 14

In [ ]:
#4. Create a 2D array with shape (4, 6) and from the 2nd and 3rd rows, slice elements from index 2 to index 5.
import numpy as np
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24]])

print(arr)
print(arr.shape)
print(arr[1:3, 2:6 ])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
(4, 6)
[[ 9 10 11 12]
 [15 16 17 18]]

In [ ]:
#5. Convert a 1D array with 12 elements into a 3D array with shape (2, 3, 2). The outermost dimension will have 2 arrays that contain 3 arrays, each with 2 elements.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

In [ ]:
#6. Create a 1D array of 15 elements and reshape it into a 3x5 matrix. Then, extract the 2nd row as a 1D array.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
newarr=arr.reshape(3,5)

print(newarr)
print("Extracted data: 2nd row")
print(newarr[1, 0:6])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Extracted data: 2nd row
[ 6  7  8  9 10]

In [ ]:
#7. Create a 3D array with shape (2, 4, 3) and from the 1st array, slice elements from the 2nd and 3rd rows
import numpy as np
arr=np.array([[[1,2,3],[5,6,7],[9,10,11],[12,13,14]],[[13,14,15],[21,22,23],[1,2,3],[1,2,34]]])
print(arr)

print(arr[0,1:3, 0:])

[[[ 1  2  3]
  [ 5  6  7]
  [ 9 10 11]
  [12 13 14]]

 [[13 14 15]
  [21 22 23]
  [ 1  2  3]
  [ 1  2 34]]]
[[ 5  6  7]
 [ 9 10 11]]

In [ ]:
#8. Create a filter array that will return only even elements from the original array.
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])

filter_arr=[]

for element in arr:
  if element % 2 == 0:
   filter_arr.append(True)
  else:
   filter_arr.append(False)

newarr=arr[filter_arr]

print(newarr)

[ 2  4  6  8 10]

In [1]:
#9. quantities_sold = [15, 22, 8, 35, 12, 25]  and price_per_item = [2.99, 5.49, 9.99, 1.99, 3.49, 4.99]. Now, Convert quantities_sold and price_per_item to numpy arrays, calculate the total sales for each product as total_sales = quantities_sold * price_per_item, and print the total sales and average price per item.
import numpy as np
quantities_sold = [15, 22, 8, 35, 12, 25]
price_per_item = [2.99, 5.49, 9.99, 1.99, 3.49, 4.99]

quantities_sold_np = np.array(quantities_sold)
price_per_item_np = np.array(price_per_item)

total_sales = quantities_sold_np * price_per_item_np
average_price = np.mean(price_per_item_np)

print(total_sales)
print(average_price)

[ 44.85 120.78  79.92  69.65  41.88 124.75]
4.823333333333333

In [2]:
#10. math_scores = [88, 92, 85, 78, 90, 84] , science_scores = [91, 85, 87, 90, 88, 86] , english_scores = [82, 89, 88, 84, 91, 87]. Now, Convert math_scores, science_scores, and english_scores to numpy arrays, calculate each studentâ€™s average score across the three subjects, and print the averages.
import numpy as np
math_scores = [88, 92, 85, 78, 90, 84]
science_scores = [91, 85, 87, 90, 88, 86]
english_scores = [82, 89, 88, 84, 91, 87]

math_scores_np=np.array(math_scores)
science_scores_np=np.array(science_scores)
english_scores_np=np.array(english_scores)

average=(math_scores_np+science_scores_np+english_scores_np)/3

print(average)

[87.         88.66666667 86.66666667 84.         89.66666667 85.66666667]

In [3]:
#11. Given the dictionary inventory = {"apple": 10, "banana": 5, "orange": 8, "grape": 3, "mango": 6}, write a program to update quantities with "banana": 3, "apple": 4, remove "grape", and check if "mango" exist or not.
inventory = {"apple": 10, "banana": 5, "orange": 8, "grape": 3, "mango": 6}

inventory["banana"] = 3
inventory["apple"] = 4

inventory.pop("grape", None)

mango_exists = "mango" in inventory
print(inventory)
print(mango_exists)

{'apple': 4, 'banana': 3, 'orange': 8, 'mango': 6}
True

In [4]:
#12. Given the dictionary grades = {"Alice": 85, "Bob": 67, "Charlie": 90, "David": 72, "Eve": 58}, write a program to print students scoring above 70, add "Frank": 76, remove "Eve", and check if "George" exist or not.
inventory= {"Alice": 85, "Bob": 67, "Charlie": 90, "David": 72, "Eve": 58}

for student, score in inventory.items():
    if score > 70:
        print(f"{student}={score}")

inventory["Frank"]=76
inventory.pop("Eve",None)
george_exit="George" in inventory

print(inventory)
print(george_exit)

Alice=85
Charlie=90
David=72
{'Alice': 85, 'Bob': 67, 'Charlie': 90, 'David': 72, 'Frank': 76}
False